// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Formatting", "RCS1057:Add empty line between declarations.", Justification = "<Pending>", Scope = "type", Target = "~T:SeniorCollegeScheduler.Models.ProposedClass")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:SeniorCollegeScheduler.Controllers.UserController.Index(SeniorCollegeScheduler.Models.ViewModels.CreateInstructorCommand)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancy", "RCS1163:Unused parameter.", Justification = "<Pending>", Scope = "member", Target = "~M:SeniorCollegeScheduler.Startup.ConfigureServices(Microsoft.Extensions.DependencyInjection.IServiceCollection)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Simplification", "RCS1021:Simplify lambda expression.", Justification = "<Pending>", Scope = "member", Target = "~M:SeniorCollegeScheduler.Data.Migrations.ReaddedUSERS.Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Simplification", "RCS1021:Simplify lambda expression.", Justification = "<Pending>", Scope = "member", Target = "~M:SeniorCollegeScheduler.Data.Migrations.DroppingUSERS.Down(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Simplification", "RCS1021:Simplify lambda expression.", Justification = "<Pending>", Scope = "member", Target = "~M:SeniorCollegeScheduler.Data.Migrations.AddedInstructorTable.Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Simplification", "RCS1021:Simplify lambda expression.", Justification = "<Pending>", Scope = "member", Target = "~M:SeniorCollegeScheduler.Data.Migrations.AddedProposedClass.Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "RCS1090:Call 'ConfigureAwait(false)'.", Justification = "<Pending>", Scope = "member", Target = "~M:SeniorCollegeScheduler.Controllers.ClassController.CreateProposal~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "RCS1090:Call 'ConfigureAwait(false)'.", Justification = "<Pending>", Scope = "member", Target = "~M:SeniorCollegeScheduler.Controllers.ClassController.ProposedClassesOverview~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0037:Use inferred member name", Justification = "<Pending>", Scope = "member", Target = "~M:SeniorCollegeScheduler.Controllers.ClassController.CreateProposal(SeniorCollegeScheduler.Models.ViewModels.CreateClassCommand)~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "RCS1090:Call 'ConfigureAwait(false)'.", Justification = "<Pending>", Scope = "member", Target = "~M:SeniorCollegeScheduler.Controllers.UserController.Index(SeniorCollegeScheduler.Models.ViewModels.CreateInstructorCommand)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "RCS1090:Call 'ConfigureAwait(false)'.", Justification = "<Pending>", Scope = "member", Target = "~M:SeniorCollegeScheduler.Controllers.UserController.ViewInstructorDetails~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:SeniorCollegeScheduler.Controllers.ClassController.CreateProposal(SeniorCollegeScheduler.Models.ViewModels.CreateClassCommand)~Microsoft.AspNetCore.Mvc.IActionResult")]